version: "3.7"

services:
  nginxrmq:
    build: nginx/.
    ports:
      - "5000:5000"
      - "15000:15000"

  rabbitmq1:
    build: rabbitmq/.
    environment:
      - RABBITMQ_CONFIG_FILE=/etc/rabbitmq/rabbitmq-custom
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log [{console,[{level,debug}]}]
      - RABBITMQ_NODENAME=rabbit@rabbitmq1
    ports:
      - "5600:5672"
      - "15600:15672"

  rabbitmq2:
    build: rabbitmq/.
    environment:
      - RABBITMQ_CONFIG_FILE=/etc/rabbitmq/rabbitmq-custom
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log [{console,[{level,debug}]}]
      - RABBITMQ_NODENAME=rabbit@rabbitmq2
    ports:
      - "5700:5672"
      - "15700:15672"